# -*- Makefile -*-

# --------------------------------------------------------------------
arch = $(shell uname)

ifneq ($(findstring CYGWIN,$(arch)),)
buildtype = cygwin
ifneq ($(findstring WOW64,$(arch)),)
cygarch   = win64
else
ifneq ($(findstring x86,$(PROCESSOR_ARCHITECTURE)),)
cygarch   = win32
else
cygarch   = win64
endif
endif
else
buildtype = unix
cygarch   =
endif

# --------------------------------------------------------------------
ifeq ($(buildtype),unix)
msbuild := xbuild
z3exe   := z3
tar 	:= gtar
endif

ifeq ($(buildtype),cygwin)

vs2015 := $(shell ls -d "/cygdrive/c/Program Files (x86)/MSBuild/14.0/" | tail -n 0)
ifeq (,$(vs2015))
msbuild := "/cygdrive/c/Program Files (x86)/MSBuild/14.0/Bin/MSBuild.exe"
else
msbuild := "/cygdrive/c/Program Files (x86)/MSBuild/12.0/Bin/MSBuild.exe"
endif

z3exe   := z3-$(cygarch:win%=x%).exe
tar 	:= tar
endif

msbuild += /nologo

